FROM apache/airflow:latest

USER root
RUN apt-get update && apt-get install -y --no-install-recommends sshpass && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --no-cache-dir \
    apache-airflow-providers-google \
    sqlalchemy \
    faker \
    psycopg2-binary \
    dbt-core \
    dbt-bigquery \
    discord_webhook

RUN airflow db migrate
